# Generated by Django 3.1.1 on 2020-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='comment',
            field=models.CharField(default='not available', max_length=70),
        ),
    ]
